//! You can contribute project ideas in this array. Make sure to add ID in consequential order.
export const data = [
  { id: 1, idea: "A Simple To-Do List App" },
  { id: 2, idea: "Create a Simple Timer." },
  { id: 3, idea: "Build an Image Carousel From Scratch." },
  { id: 4, idea: "Web Calculator." },
  { id: 5, idea: "Resume Generator." },
  { id: 6, idea: "Build a Browser Extension." },
  { id: 7, idea: "Build a Budgeting Application." },
  { id: 8, idea: "Unit Converter." },
  { id: 9, idea: "Create a Diary." },
  { id: 10, idea: "Brick Breaker Game." },
  { id: 11, idea: "ASCII Analog/Digital Clock." },
  { id: 12, idea: "Tic Tac Toe game." },
  { id: 13, idea: "Flappy Bird game." },
  { id: 14, idea: "Make a Quiz app." },
  { id: 15, idea: "MS Paint clone." },
  { id: 16, idea: "Create a database." },
  { id: 17, idea: "Weather app." },
  { id: 18, idea: "Markdown Editor." },
  { id: 19, idea: "E-commerce app like Amazon." },
  {
    id: 20,
    idea: "File's extension convertor (like .jpg to .png).",
  },
  { id: 21, idea: "Code editor like VS code." },
  { id: 22, idea: "Password Generator app." },
  { id: 23, idea: "Snake game." },
  { id: 24, idea: "Minesweeper game." },
  { id: 25, idea: "Connect 4 game." },
]
